behaviors:
  Shooter:
    trainer_type: ppo
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0003
      beta: 0.01
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 512
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      curiosity:
        gamma: 0.99
        strength: 0.02
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
    keep_checkpoints: 5
    max_steps: 10000000
    time_horizon: 128
    summary_freq: 30000
environment_parameters:
  normal_enemy_spawn_rate:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 100
        value: 5
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 120
        value: 4
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 140
        value: 3
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 150
        value: 2.5
      - name: Lesson5
        value: 2  
  big_enemy_spawn_rate:
    curriculum:
      - name: Lesson1
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 100
        value: 12
      - name: Lesson2
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 120
        value: 11
      - name: Lesson3
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 140
        value: 10
      - name: Lesson4
        completion_criteria:
          measure: reward
          behavior: Shooter
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 150
        value: 9
      - name: Lesson5
        value: 8  
  